1. buat vector x dengan ukuran 3x1

In [2]:
import numpy as np

In [3]:
# buat vector x dengan ukuran 3x1
x = np.array([[1],
              [0],
              [0]])
x

array([[1],
       [0],
       [0]])

In [4]:
# hitung panjang vector x
len(x)

3

In [5]:
# tampilkan ukuran vector x
x.shape

(3, 1)

In [6]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [7]:
# akses elemen pertama dari vector x
x[0] # zero-indexed

array([1])

In [8]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

2. akukan transpose pada vector x dan simpan pada variabel x_t

In [9]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([[1, 0, 0]])

In [10]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [17]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[1],
              [0],
              [0]])
y_t = y.T
y_t

array([[1, 0, 0]])

In [18]:
# tampilkan ukuran dari vector y_t
y_t.shape


(1, 3)

3. lakukan soal nomor 2 menggunakan pytorch dan tensorflow

In [20]:
import torch as pt

In [21]:
x = pt.tensor([[1],
               [0],
               [0]])
x

tensor([[1],
        [0],
        [0]])

In [22]:
x_t = x.T
x_t

tensor([[1, 0, 0]])

In [23]:
x_t.shape

torch.Size([1, 3])

In [24]:
y = pt.tensor([[1],
               [0],
               [0]])
y


tensor([[1],
        [0],
        [0]])

In [25]:
y_t = y.T
y_t

tensor([[1, 0, 0]])

In [26]:
import tensorflow as tf

In [27]:
x = tf.constant([[1],
                 [0],
                 [0]])
x

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [0],
       [0]], dtype=int32)>

In [28]:
x_t = tf.transpose(x)
x_t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 0, 0]], dtype=int32)>

In [29]:
y = tf.constant([[1],
                 [0],
                 [0]])
y

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [0],
       [0]], dtype=int32)>

In [30]:
y_t = tf.transpose(y)
y_t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 0, 0]], dtype=int32)>